### ISSUE TITLE
Using lightadaptor, jsdomadaptor: \underbrace causes SVG output to throw

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-src#500]
I'm running into the following issue with v3.0.5.

```js
const mathjax_1 = require("mathjax-full/js/mathjax");
const tex_1 = require("mathjax-full/js/input/tex");
const svg_1 = require("mathjax-full/js/output/svg");
const liteAdaptor_1 = require("mathjax-full/js/adaptors/liteAdaptor");
const html_1 = require("mathjax-full/js/handlers/html");
const AllPackages_1 = require("mathjax-full/js/input/tex/AllPackages");
const adaptor = liteAdaptor_1.liteAdaptor();
html_1.RegisterHTMLHandler(adaptor);
const tex = new tex_1.TeX({ packages: AllPackages_1.AllPackages });
const svg = new svg_1.SVG({ fontCache: "none" });
const mathDocument = mathjax_1.mathjax.document("", { InputJax: tex, OutputJax: svg });

console.log(adaptor.outerHTML(mathDocument.convert('\\underbrace{x}')));


//            finally { if (e_4) throw e_4.error; }
//                                ^

// TypeError: Cannot read property 'chars' of undefined
//     at SVGmo.CommonWrapper.unicodeChars (/node_modules/mathjax-full/js/output/common/Wrapper.js:433:48)
//     at SVGmo.SVGWrapper.placeChar (/node_modules/mathjax-full/js/output/svg/Wrapper.js:206:45)
//     at SVGmo.addGlyph (/node_modules/mathjax-full/js/output/svg/Wrappers/mo.js:109:21)
//     at SVGmo.addMidH (/node_modules/mathjax-full/js/output/svg/Wrappers/mo.js:194:14)
//     at SVGmo.stretchHorizontal (/node_modules/mathjax-full/js/output/svg/Wrappers/mo.js:94:34)
//     at SVGmo.stretchSVG (/node_modules/mathjax-full/js/output/svg/Wrappers/mo.js:73:18)
//     at SVGmo.toSVG (/node_modules/mathjax-full/js/output/svg/Wrappers/mo.js:52:18)
//     at SVGmunder.toSVG (/node_modules/mathjax-full/js/output/svg/Wrappers/munderover.js:51:16)
//     at SVGinferredMrow.SVGWrapper.addChildren (/node_modules/mathjax-full/js/output/svg/Wrapper.js:61:23)
//     at SVGinferredMrow.SVGmrow.toSVG (/node_modules/mathjax-full/js/output/svg/Wrappers/mrow.js:27:14)
```

**Comment by pkra** [comment]
Same for jsdom adaptor (which could benefit from some documentation).

**Comment by pkra** [comment]
I'm guessing a duplicate of https://github.com/mathjax/MathJax-src/pull/477 / https://github.com/mathjax/MathJax/issues/2402.

**Comment by dpvc** [comment]
> I'm guessing a duplicate of #477

Yes, that is correct.  Thanks for figuring that out.
