### ISSUE TITLE
v4: using font variants crashes on nodejs

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-src#867]
E.g., using `mathsf` throws an error on nodejs:

```
Can't load './output/svg/fonts/svg/dynamic/sans-serif': No asyncLoad method specified
.../node_modules/mathjax-full/js/util/Retries.js:25
    var err = new Error('MathJax retry');
              ^

Error: MathJax retry
    at retryAfter (.../node_modules/mathjax-full/js/util/Retries.js:25:15)
    at FontData.getChar (.../node_modules/mathjax-full/js/output/common/FontData.js:580:41)
```

Similarly for `\texttt` etc.

**Comment by dpvc** [comment]
The section of the release notes on [promises](https://mathjax.github.io/MathJax-demos-web/convert-configuration/convert-configuration.html) talks a bit about this.  You need to load the `util/asyncLoad/node.js` file in order to support this.  See the last paragraph of that section, which also indicates how to load all the font data up front.
